/**
 * Invoice Generation Service
 * Creates professional bilingual invoices from project data
 * Generates PDF with jsPDF and integrates with workflow
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Project,
  ProjectStatus,
  Invoice,
  LineItem,
  Client
} from '../types/project';
import { projectStorage, clientStorage, invoiceStorage, rateCardStorage } from './projectStorage';
import { Language } from '../types';

// ============================================
// TRANSLATIONS
// ============================================

const translations = {
  EN: {
    invoice: 'INVOICE',
    billTo: 'BILL TO',
    shipTo: 'PROJECT LOCATION',
    invoiceNumber: 'Invoice #',
    date: 'Date',
    dueDate: 'Due Date',
    terms: 'Terms',
    mapCode: 'Map Code',
    project: 'Project',
    description: 'Description',
    qty: 'Qty',
    unit: 'Unit',
    rate: 'Rate',
    amount: 'Amount',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'TOTAL DUE',
    footer: 'Thank you for your business!',
    paymentTerms: 'NET 30',
    generatedBy: 'Generated by NextGen Fiber AI',
    aerialInstallation: 'Aerial Fiber Installation',
    undergroundInstallation: 'Underground Fiber Installation',
    overlashInstallation: 'Overlash Installation',
    anchorInstallation: 'Anchor Installation',
    coilInstallation: 'Coil Installation',
    snowshoeInstallation: 'Snowshoe Installation',
    feet: 'FT',
    each: 'EA',
    lineman: 'Lineman',
    workDate: 'Work Date',
    compliance: 'Compliance Score'
  },
  PT: {
    invoice: 'FATURA',
    billTo: 'FATURAR PARA',
    shipTo: 'LOCAL DO PROJETO',
    invoiceNumber: 'Fatura #',
    date: 'Data',
    dueDate: 'Vencimento',
    terms: 'Condições',
    mapCode: 'Código do Mapa',
    project: 'Projeto',
    description: 'Descrição',
    qty: 'Qtd',
    unit: 'Un.',
    rate: 'Taxa',
    amount: 'Valor',
    subtotal: 'Subtotal',
    tax: 'Imposto',
    total: 'TOTAL A PAGAR',
    footer: 'Obrigado pela preferência!',
    paymentTerms: 'NET 30',
    generatedBy: 'Gerado por NextGen Fiber AI',
    aerialInstallation: 'Instalação de Fibra Aérea',
    undergroundInstallation: 'Instalação de Fibra Subterrânea',
    overlashInstallation: 'Instalação de Overlash',
    anchorInstallation: 'Instalação de Âncora',
    coilInstallation: 'Instalação de Bobina',
    snowshoeInstallation: 'Instalação de Snowshoe',
    feet: 'PÉS',
    each: 'UN',
    lineman: 'Técnico',
    workDate: 'Data do Trabalho',
    compliance: 'Pontuação de Conformidade'
  },
  ES: {
    invoice: 'FACTURA',
    billTo: 'FACTURAR A',
    shipTo: 'UBICACIÓN DEL PROYECTO',
    invoiceNumber: 'Factura #',
    date: 'Fecha',
    dueDate: 'Vencimiento',
    terms: 'Condiciones',
    mapCode: 'Código del Mapa',
    project: 'Proyecto',
    description: 'Descripción',
    qty: 'Cant',
    unit: 'Un.',
    rate: 'Tarifa',
    amount: 'Importe',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    total: 'TOTAL A PAGAR',
    footer: '¡Gracias por su preferencia!',
    paymentTerms: 'NET 30',
    generatedBy: 'Generado por NextGen Fiber AI',
    aerialInstallation: 'Instalación de Fibra Aérea',
    undergroundInstallation: 'Instalación de Fibra Subterránea',
    overlashInstallation: 'Instalación de Overlash',
    anchorInstallation: 'Instalación de Ancla',
    coilInstallation: 'Instalación de Bobina',
    snowshoeInstallation: 'Instalación de Snowshoe',
    feet: 'PIES',
    each: 'UN',
    lineman: 'Técnico',
    workDate: 'Fecha del Trabajo',
    compliance: 'Puntuación de Cumplimiento'
  }
};

// ============================================
// COMPANY INFO (would come from settings)
// ============================================

const COMPANY_INFO = {
  name: 'NextGen Fiber Construction LLC',
  address: '1234 Fiber Lane',
  city: 'Ashburn',
  state: 'VA',
  zipCode: '20147',
  phone: '(703) 555-0100',
  email: 'billing@nextgenfiber.com',
  website: 'www.nextgenfiber.com'
};

// ============================================
// INVOICE GENERATION
// ============================================

/**
 * Generate invoice from project
 */
export const generateInvoiceFromProject = async (
  projectId: string,
  options: {
    taxRate?: number;
    notes?: string;
    notes_pt?: string;
    dueDays?: number;
  } = {}
): Promise<Invoice | null> => {
  const project = projectStorage.getById(projectId);
  if (!project) {
    console.error(`[Invoice] Project ${projectId} not found`);
    return null;
  }

  if (project.status !== ProjectStatus.READY_TO_INVOICE && project.status !== ProjectStatus.AI_COMPLETE) {
    console.error(`[Invoice] Project ${projectId} is not ready for invoicing (status: ${project.status})`);
    return null;
  }

  const client = clientStorage.getById(project.clientId);
  const taxRate = options.taxRate || 0;
  const dueDays = options.dueDays || 30;
  const now = new Date();
  const dueDate = new Date(now.getTime() + dueDays * 24 * 60 * 60 * 1000);

  // Calculate totals
  const subtotal = project.lineItems.reduce((sum, item) => sum + item.total, 0);
  const tax = subtotal * taxRate;
  const total = subtotal + tax;

  // Create invoice
  const invoice = invoiceStorage.create({
    projectId: project.id,
    clientId: project.clientId,
    lineItems: project.lineItems,
    subtotal,
    tax,
    taxRate,
    total,
    status: 'draft',
    dueDate: dueDate.toISOString().split('T')[0],
    notes: options.notes,
    notes_pt: options.notes_pt
  });

  // Update project with invoice reference
  projectStorage.update(projectId, {
    status: ProjectStatus.INVOICED,
    invoiceId: invoice.id,
    invoice
  });

  projectStorage.addEvent(projectId, {
    action: 'invoice_generated',
    description: `Invoice ${invoice.invoiceNumber} generated`,
    metadata: { invoiceId: invoice.id, total }
  });

  console.log(`[Invoice] Generated ${invoice.invoiceNumber} for project ${project.mapCode}`);

  return invoice;
};

/**
 * Generate PDF from invoice
 */
export const generateInvoicePDF = (
  invoice: Invoice,
  project: Project,
  lang: Language = Language.EN
): Blob => {
  const t = translations[lang];
  const client = clientStorage.getById(invoice.clientId);
  const doc = new jsPDF();

  // Colors
  const primaryColor: [number, number, number] = [0, 212, 255]; // Neural cyan
  const darkColor: [number, number, number] = [11, 17, 33]; // Void
  const grayColor: [number, number, number] = [100, 116, 139];

  // Header - Company Logo area
  doc.setFillColor(...darkColor);
  doc.rect(0, 0, 220, 45, 'F');

  // Company name
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(COMPANY_INFO.name, 20, 20);

  // Company details
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text(`${COMPANY_INFO.address}`, 20, 28);
  doc.text(`${COMPANY_INFO.city}, ${COMPANY_INFO.state} ${COMPANY_INFO.zipCode}`, 20, 34);
  doc.text(`${COMPANY_INFO.phone} | ${COMPANY_INFO.email}`, 20, 40);

  // Invoice title
  doc.setFontSize(28);
  doc.setTextColor(...primaryColor);
  doc.text(t.invoice, 195, 25, { align: 'right' });

  // Invoice number box
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(`${t.invoiceNumber}: ${invoice.invoiceNumber}`, 195, 35, { align: 'right' });

  // Invoice details section
  let y = 55;

  // Date and Due Date
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text(`${t.date}:`, 140, y);
  doc.text(`${t.dueDate}:`, 140, y + 6);
  doc.text(`${t.terms}:`, 140, y + 12);
  doc.text(`${t.mapCode}:`, 140, y + 18);

  doc.setTextColor(0, 0, 0);
  doc.text(new Date(invoice.createdAt).toLocaleDateString(), 195, y, { align: 'right' });
  doc.text(invoice.dueDate || '-', 195, y + 6, { align: 'right' });
  doc.text(t.paymentTerms, 195, y + 12, { align: 'right' });
  doc.text(project.mapCode, 195, y + 18, { align: 'right' });

  // Bill To section
  doc.setFontSize(10);
  doc.setTextColor(...primaryColor);
  doc.text(t.billTo, 20, y);

  y += 7;
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(client?.name || 'Client', 20, y);

  if (client?.address) {
    y += 5;
    doc.setFontSize(9);
    doc.setTextColor(...grayColor);
    doc.text(client.address, 20, y);
  }

  if (client?.email) {
    y += 5;
    doc.text(client.email, 20, y);
  }

  // Project Location section
  y += 12;
  doc.setFontSize(10);
  doc.setTextColor(...primaryColor);
  doc.text(t.shipTo, 20, y);

  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  if (project.location?.address) {
    doc.text(project.location.address, 20, y);
    y += 5;
  }
  doc.setTextColor(...grayColor);
  doc.text(`${t.lineman}: ${project.linemanName}`, 20, y);
  y += 5;
  doc.text(`${t.workDate}: ${new Date(project.workDate).toLocaleDateString()}`, 20, y);

  if (project.aiAnalysis) {
    y += 5;
    doc.text(`${t.compliance}: ${project.aiAnalysis.complianceScore}%`, 20, y);
  }

  // Line Items Table
  y += 15;

  const tableData = invoice.lineItems.map(item => {
    // Translate description if PT/ES
    let description = item.description;
    if (lang !== Language.EN && item.description_pt) {
      description = item.description_pt;
    }

    return [
      description,
      item.quantity.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 }),
      item.unit === 'ft' ? t.feet : item.unit === 'each' ? t.each : item.unit.toUpperCase(),
      `$${item.unitPrice.toFixed(2)}`,
      `$${item.total.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [[t.description, t.qty, t.unit, t.rate, t.amount]],
    body: tableData,
    theme: 'plain',
    headStyles: {
      fillColor: darkColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
      cellPadding: 4
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 4
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { halign: 'right', cellWidth: 25 },
      2: { halign: 'center', cellWidth: 20 },
      3: { halign: 'right', cellWidth: 30 },
      4: { halign: 'right', cellWidth: 35 }
    },
    margin: { left: 20, right: 20 }
  });

  // Totals section
  const tableEndY = (doc as any).lastAutoTable.finalY;
  y = tableEndY + 10;

  // Draw totals box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(120, y - 5, 75, invoice.taxRate > 0 ? 40 : 30, 3, 3, 'F');

  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text(t.subtotal, 125, y + 5);
  doc.setTextColor(0, 0, 0);
  doc.text(`$${invoice.subtotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y + 5, { align: 'right' });

  if (invoice.taxRate > 0) {
    y += 10;
    doc.setTextColor(...grayColor);
    doc.text(`${t.tax} (${(invoice.taxRate * 100).toFixed(1)}%)`, 125, y + 5);
    doc.setTextColor(0, 0, 0);
    doc.text(`$${invoice.tax.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y + 5, { align: 'right' });
  }

  y += 12;
  doc.setFillColor(...primaryColor);
  doc.roundedRect(120, y, 75, 12, 2, 2, 'F');

  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(t.total, 125, y + 8);
  doc.text(`$${invoice.total.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y + 8, { align: 'right' });

  // Notes section
  if (invoice.notes || invoice.notes_pt) {
    y += 25;
    doc.setFontSize(8);
    doc.setTextColor(...grayColor);
    const notes = lang === Language.PT && invoice.notes_pt ? invoice.notes_pt : invoice.notes;
    if (notes) {
      const splitNotes = doc.splitTextToSize(notes, 170);
      doc.text(splitNotes, 20, y);
    }
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(...primaryColor);
  doc.text(t.footer, 105, 270, { align: 'center' });

  doc.setFontSize(7);
  doc.setTextColor(...grayColor);
  doc.text(`${t.generatedBy} - ${new Date().toLocaleString()}`, 105, 280, { align: 'center' });

  // Return as blob
  return doc.output('blob');
};

/**
 * Generate and download invoice PDF
 */
export const downloadInvoicePDF = (
  invoice: Invoice,
  project: Project,
  lang: Language = Language.EN
): void => {
  const blob = generateInvoicePDF(invoice, project, lang);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `invoice_${invoice.invoiceNumber}_${lang.toLowerCase()}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Generate bilingual invoices (EN + PT)
 */
export const generateBilingualInvoices = async (
  projectId: string,
  options?: {
    taxRate?: number;
    notes?: string;
    notes_pt?: string;
  }
): Promise<{ invoice: Invoice; pdfEN: Blob; pdfPT: Blob } | null> => {
  const invoice = await generateInvoiceFromProject(projectId, options);
  if (!invoice) return null;

  const project = projectStorage.getById(projectId);
  if (!project) return null;

  const pdfEN = generateInvoicePDF(invoice, project, Language.EN);
  const pdfPT = generateInvoicePDF(invoice, project, Language.PT);

  return { invoice, pdfEN, pdfPT };
};

// ============================================
// INVOICE STATUS MANAGEMENT
// ============================================

/**
 * Mark invoice as sent
 */
export const markInvoiceSent = (invoiceId: string): Invoice | null => {
  return invoiceStorage.update(invoiceId, {
    status: 'sent',
    sentAt: new Date().toISOString()
  });
};

/**
 * Mark invoice as paid
 */
export const markInvoicePaid = (invoiceId: string): Invoice | null => {
  const invoice = invoiceStorage.update(invoiceId, {
    status: 'paid',
    paidAt: new Date().toISOString()
  });

  if (invoice) {
    // Update project status
    const project = projectStorage.getAll().find(p => p.invoiceId === invoiceId);
    if (project) {
      projectStorage.update(project.id, {
        status: ProjectStatus.PAID
      });
      projectStorage.addEvent(project.id, {
        action: 'payment_received',
        description: `Payment received for invoice ${invoice.invoiceNumber}`,
        metadata: { amount: invoice.total }
      });
    }
  }

  return invoice;
};

/**
 * Mark invoice as disputed
 */
export const markInvoiceDisputed = (invoiceId: string, reason?: string): Invoice | null => {
  const invoice = invoiceStorage.update(invoiceId, {
    status: 'disputed'
  });

  if (invoice) {
    const project = projectStorage.getAll().find(p => p.invoiceId === invoiceId);
    if (project) {
      projectStorage.update(project.id, {
        status: ProjectStatus.DISPUTED
      });
      projectStorage.addEvent(project.id, {
        action: 'invoice_disputed',
        description: `Invoice ${invoice.invoiceNumber} disputed`,
        metadata: { reason }
      });
    }
  }

  return invoice;
};

// ============================================
// EXPORT
// ============================================

export const invoiceService = {
  generateFromProject: generateInvoiceFromProject,
  generatePDF: generateInvoicePDF,
  downloadPDF: downloadInvoicePDF,
  generateBilingual: generateBilingualInvoices,
  markSent: markInvoiceSent,
  markPaid: markInvoicePaid,
  markDisputed: markInvoiceDisputed
};

export default invoiceService;
